---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: kstar
data:
  SPRING_PROFILES_ACTIVE: "docker"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: kstar
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/kstar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-config
  namespace: kstar
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/kstar_exchange"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-config
  namespace: kstar
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/kstar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  USER_SERVICE_URL: "http://user-service:8081"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bullion-config
  namespace: kstar
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/kstar_bullion"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacha-config
  namespace: kstar
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/kstar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
